In [3]:
import pandas as pd
import torch
import numpy as np

In [13]:
from data_tools.containers import StocksData, StocksTarget
from features import IndicatorsFeaturesList
from targets import ClosePriceTargetFunction
from data_tools.samplers import SimpleModelPreprocessor

In [14]:
stocks_data = StocksData(["./data/market_data/AAPL.csv", "./data/market_data/ABT.csv"])

In [15]:
stocks_data.data

high         low        open       close  \
date                                                                  
2021-01-25 14:30:00  145.080002  142.940002  143.125000  144.229996   
2021-01-25 15:30:00  144.320007  136.539993  144.229996  141.220001   
2021-01-25 16:30:00  142.949997  140.910004  141.220001  141.190002   
2021-01-25 17:30:00  143.289993  141.039993  141.179993  142.989899   
2021-01-25 18:30:00  143.250000  141.789993  143.009995  142.582001   
...                         ...         ...         ...         ...   
2023-01-12 17:30:00  112.320000  111.620003  112.050003  111.690002   
2023-01-12 18:30:00  112.099998  111.535004  111.650002  111.705002   
2023-01-12 19:30:00  111.800003  111.139999  111.699997  111.330002   
2023-01-12 20:30:00  111.489998  110.970001  111.330002  111.360001   
2023-01-12 21:00:00  111.360001  111.360001  111.360001  111.360001   

                         volume ticker  
date                                    
2021-01-25 14:30:00  46354729.0   AAPL  
2021-01-25 15:30:00  37087128.0   AAPL  
2021-01-25 16:30:00  18948572.0   AAPL  
2021-01-25 17:30:00  14505566.0   AAPL  
2021-01-25 18:30:00  11219998.0   AAPL  
...                         ...    ...  
2023-01-12 17:30:00    356463.0    ABT  
2023-01-12 18:30:00    289208.0    ABT  
2023-01-12 19:30:00    579781.0    ABT  
2023-01-12 20:30:00    861723.0    ABT  
2023-01-12 21:00:00         0.0    ABT  

[6948 rows x 6 columns]

In [16]:
stocks_data = IndicatorsFeaturesList().preprocess(stocks_data)

In [17]:
stocks_data.data

high         low        open       close  \
date                                                                  
2021-01-25 14:30:00  145.080002  142.940002  143.125000  144.229996   
2021-01-25 15:30:00  144.320007  136.539993  144.229996  141.220001   
2021-01-25 16:30:00  142.949997  140.910004  141.220001  141.190002   
2021-01-25 17:30:00  143.289993  141.039993  141.179993  142.989899   
2021-01-25 18:30:00  143.250000  141.789993  143.009995  142.582001   
...                         ...         ...         ...         ...   
2023-01-12 17:30:00  112.320000  111.620003  112.050003  111.690002   
2023-01-12 18:30:00  112.099998  111.535004  111.650002  111.705002   
2023-01-12 19:30:00  111.800003  111.139999  111.699997  111.330002   
2023-01-12 20:30:00  111.489998  110.970001  111.330002  111.360001   
2023-01-12 21:00:00  111.360001  111.360001  111.360001  111.360001   

                         volume ticker  close_5_mean  close_10_mean  \
date                                                                  
2021-01-25 14:30:00  46354729.0   AAPL           NaN            NaN   
2021-01-25 15:30:00  37087128.0   AAPL           NaN            NaN   
2021-01-25 16:30:00  18948572.0   AAPL           NaN            NaN   
2021-01-25 17:30:00  14505566.0   AAPL           NaN            NaN   
2021-01-25 18:30:00  11219998.0   AAPL    142.442380            NaN   
...                         ...    ...           ...            ...   
2023-01-12 17:30:00    356463.0    ABT    112.185001     112.564500   
2023-01-12 18:30:00    289208.0    ABT    111.904001     112.467500   
2023-01-12 19:30:00    579781.0    ABT    111.760001     112.329501   
2023-01-12 20:30:00    861723.0    ABT    111.631001     112.145000   
2023-01-12 21:00:00         0.0    ABT    111.489001     111.977000   

                     close_20_mean  close_5_var  close_10_var  close_20_var  
date                                                                         
2021-01-25 14:30:00            NaN          NaN           NaN           NaN  
2021-01-25 15:30:00            NaN          NaN           NaN           NaN  
2021-01-25 16:30:00            NaN          NaN           NaN           NaN  
2021-01-25 17:30:00            NaN          NaN           NaN           NaN  
2021-01-25 18:30:00            NaN     1.644375           NaN           NaN  
...                            ...          ...           ...           ...  
2023-01-12 17:30:00     112.944735     0.291125      0.314497      0.506897  
2023-01-12 18:30:00     112.915435     0.036117      0.384767      0.564392  
2023-01-12 19:30:00     112.874935     0.087237      0.500840      0.663312  
2023-01-12 20:30:00     112.764435     0.091430      0.482288      0.745823  
2023-01-12 21:00:00     112.671935     0.036405      0.430394      0.830180  

[6948 rows x 12 columns]

In [18]:
target = StocksTarget.from_target_function(stocks_data, ClosePriceTargetFunction(2))

In [20]:
target.get_data()

close_target_2_bars ticker
date                                           
2021-01-25 14:30:00           141.190002   AAPL
2021-01-25 15:30:00           142.989899   AAPL
2021-01-25 16:30:00           142.582001   AAPL
2021-01-25 17:30:00           142.070007   AAPL
2021-01-25 18:30:00           142.899994   AAPL
...                                  ...    ...
2023-01-12 17:30:00           111.330002    ABT
2023-01-12 18:30:00           111.360001    ABT
2023-01-12 19:30:00           111.360001    ABT
2023-01-12 20:30:00                  NaN    ABT
2023-01-12 21:00:00                  NaN    ABT

[6948 rows x 2 columns]

In [21]:
X, y = SimpleModelPreprocessor.preprocess(stocks_data, target)

In [16]:
slice(None, 1, 2).start

In [22]:
X

array([[1.45080002e+02, 1.42940002e+02, 1.43125000e+02, ...,
                   nan,            nan,            nan],
       [1.44320007e+02, 1.36539993e+02, 1.44229996e+02, ...,
                   nan,            nan,            nan],
       [1.42949997e+02, 1.40910004e+02, 1.41220001e+02, ...,
                   nan,            nan,            nan],
       ...,
       [1.12320000e+02, 1.11620003e+02, 1.12050003e+02, ...,
        2.91124737e-01, 3.14496545e-01, 5.06896806e-01],
       [1.12099998e+02, 1.11535004e+02, 1.11650002e+02, ...,
        3.61171153e-02, 3.84767297e-01, 5.64391522e-01],
       [1.11800003e+02, 1.11139999e+02, 1.11699997e+02, ...,
        8.72365868e-02, 5.00840395e-01, 6.63312216e-01]])

In [23]:
y

array([141.19000244, 142.98989868, 142.58200073, ..., 111.33000183,
       111.36000061, 111.36000061])

In [10]:
a = torch.rand(size=(4, 5))
b = torch.rand(size=(3, 5))
c = torch.rand(size=(5, 5))
torch.nn.utils.rnn.pad_sequence([a, b, c], batch_first=True)

tensor([[[0.4906, 0.5951, 0.7632, 0.2708, 0.4830],
         [0.3416, 0.1432, 0.7114, 0.5706, 0.9816],
         [0.1728, 0.8337, 0.1146, 0.1179, 0.9208],
         [0.1169, 0.1710, 0.2029, 0.8942, 0.9075],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

        [[0.7109, 0.0180, 0.6380, 0.2420, 0.7028],
         [0.2725, 0.1390, 0.8713, 0.5950, 0.3568],
         [0.1305, 0.5856, 0.0830, 0.1538, 0.3662],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

        [[0.5190, 0.6408, 0.0852, 0.2307, 0.0853],
         [0.1962, 0.7065, 0.2285, 0.5728, 0.2882],
         [0.6352, 0.2560, 0.0556, 0.8341, 0.6023],
         [0.3666, 0.5220, 0.6428, 0.7005, 0.6356],
         [0.5691, 0.3541, 0.7400, 0.2112, 0.3621]]])